apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  {{- template "common.metadata" . }}
spec:
  {{ if .Values.app.testing }}
  type: LoadBalancer
  {{ end }}
  ports:
    - port: 443
      protocol: TCP
      targetPort: 1337
  selector:
    app: {{ .Values.app.name }}
---