{{ if and (eq .Values.app.kVerMajor "1") (eq .Values.app.kVerMinor "15") }}
apiVersion: apps/v1beta1
{{ else }}
apiVersion: apps/v1
{{ end }}
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  {{- template "common.metadata" . }}
spec:
  {{ if and (eq .Values.app.kVerMajor "1") (gt .Values.app.kVerMinor "15") }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  {{ end }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      nodeSelector: {{ .Values.nodeSelector }}
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.app.image }}
          imagePullPolicy: IfNotPresent
          env: 
           
          ports:
            - containerPort: 1337
          resources:
            requests:
              cpu: 200m
            limits:
              cpu: 300m
          volumeMounts:
            - name: webhook-certs
              mountPath: /mnt/webhook
              readOnly: true
           
      serviceAccount: {{ $.Values.app.name }}
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ .Values.app.name }}
        
---
