apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: test-rs
  annotations:
    appinsights.connstr: InstrumentationKey=e322c236-0547-483d-bcb7-e28d3dba11f1;IngestionEndpoint=https://eastasia-0.in.applicationinsights.azure.com/;LiveEndpoint=https://eastasia.livediagnostics.monitor.azure.com/
    appinsights.role: department-service
  
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: javademo
  template:
    metadata:
      labels:
        app: javademo
    spec:
      containers:
        - name: javademo-mutate
          image: cloudfyy/akswebhookjavademo:2.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          command: ["/bin/sh", "-c", "java -jar /app/demo.jar"]
