# test-deploy1.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-test-deploy
  annotations:
    appinsights.connstr: InstrumentationKey=e322c236-0547-483d-bcb7-e28d3dba11f1;IngestionEndpoint=https://eastasia-0.in.applicationinsights.azure.com/;LiveEndpoint=https://eastasia.livediagnostics.monitor.azure.com/
    appinsights.role: department-service
spec:
  selector:
    matchLabels:
      app: javademo
  template:
    metadata:
      labels:
        app: javademo
    spec:
      containers:
        - name: javademo-mutate
          image: cloudfyy/akswebhookjavademo:2.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          command: ["/bin/sh", "-c", "java -jar /app/demo.jar"]
---
apiVersion: v1
kind: Service
metadata:
  name: javademo-svc
spec:
  selector:
    app: javademo
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
