apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    appinsights.connstr: InstrumentationKey=ed9baecd-d00e-46fd-a584-baefb918ca65;IngestionEndpoint=https://japaneast-1.in.applicationinsights.azure.com/;LiveEndpoint=https://japaneast.livediagnostics.monitor.azure.com/
    appinsights.role: department-service
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"appinsights.connstr":"InstrumentationKey=ed9baecd-d00e-46fd-a584-baefb918ca65;IngestionEndpoint=https://japaneast-1.in.applicationinsights.azure.com/;LiveEndpoint=https://japaneast.livediagnostics.monitor.azure.com/","appinsights.role":"department-service"},"name":"java-test-deploy","namespace":"default"},"spec":{"selector":{"matchLabels":{"app":"javademo"}},"template":{"metadata":{"labels":{"app":"javademo"}},"spec":{"containers":[{"command":["/bin/sh","-c","java -jar /opt/demo/demo.jar"],"image":"cloudfyy/akswebhookjavademo:2.2","imagePullPolicy":"Always","name":"javademo-mutate","ports":[{"containerPort":8080}]}]}}}}
  creationTimestamp: "2023-05-07T02:10:57Z"
  generation: 1
  name: java-test-deploy
  namespace: default
  resourceVersion: "75917249"
  uid: 41e3bd88-7235-49be-a72d-2bef4e098651
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: javademo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: javademo
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - java -jar /opt/demo/demo.jar
        image: cloudfyy/akswebhookjavademo:2.2
        imagePullPolicy: Always
        name: javademo-mutate
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2023-05-07T02:10:57Z"
    lastUpdateTime: "2023-05-07T02:10:57Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2023-05-07T02:10:57Z"
    lastUpdateTime: "2023-05-07T02:10:57Z"
    message: ReplicaSet "java-test-deploy-7689b96d64" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
