apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    appinsights.connstr: InstrumentationKey=ed9baecd-d00e-46fd-a584-baefb918ca65;IngestionEndpoint=https://japaneast-1.in.applicationinsights.azure.com/;LiveEndpoint=https://japaneast.livediagnostics.monitor.azure.com/
    appinsights.role: department-service
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "2"
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-05-07T02:10:57Z"
  generation: 1
  labels:
    app: javademo
    pod-template-hash: 7689b96d64
  name: java-test-deploy-7689b96d64
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: java-test-deploy
    uid: 41e3bd88-7235-49be-a72d-2bef4e098651
  resourceVersion: "75917247"
  uid: eba0449a-fa74-408d-ab77-041ab9f4f0e0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javademo
      pod-template-hash: 7689b96d64
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: javademo
        pod-template-hash: 7689b96d64
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - java -jar /opt/demo/demo.jar
        image: cloudfyy/akswebhookjavademo:2.2
        imagePullPolicy: Always
        name: javademo-mutate
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  fullyLabeledReplicas: 1
  observedGeneration: 1
  replicas: 1
