apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    appinsights.connstr: InstrumentationKey=ed9baecd-d00e-46fd-a584-baefb918ca65;IngestionEndpoint=https://japaneast-1.in.applicationinsights.azure.com/;LiveEndpoint=https://japaneast.livediagnostics.monitor.azure.com/
    appinsights.role: department-service
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "2"
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-05-06T04:13:55Z"
  generation: 1
  labels:
    app: javademo
    pod-template-hash: 86c9d59fb6
  name: java-test-deploy-86c9d59fb6
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: java-test-deploy
    uid: fb097c30-fab2-47da-8bc5-4a05d7d4e176
  resourceVersion: "75583927"
  uid: ed2b9dd9-c7be-4be3-acaa-59efef7bc049
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javademo
      pod-template-hash: 86c9d59fb6
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: javademo
        pod-template-hash: 86c9d59fb6
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - java -jar /opt/demo/demo.jar
        env:
        - name: appinsights.connstr
          value: InstrumentationKey=ed9baecd-d00e-46fd-a584-baefb918ca65;IngestionEndpoint=https://japaneast-1.in.applicationinsights.azure.com/;LiveEndpoint=https://japaneast.livediagnostics.monitor.azure.com/
        - name: appinsights.role
          value: department-service
        - name: JAVA_TOOL_OPTIONS
          value: -javaagent:/opt/aiagent/applicationinsights-agent-3.4.10.jar
        image: cloudfyy/akswebhookjavademo:2.2
        imagePullPolicy: Always
        name: javademo-mutate
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config/
          name: appinsights-config
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - /bin/sh
        - -c
        - source /app/init-appinsights.sh; cp /app/* /config/
        env:
        - name: appinsights.connstr
          value: InstrumentationKey=ed9baecd-d00e-46fd-a584-baefb918ca65;IngestionEndpoint=https://japaneast-1.in.applicationinsights.azure.com/;LiveEndpoint=https://japaneast.livediagnostics.monitor.azure.com/
        - name: appinsights.role
          value: department-service
        - name: JAVA_TOOL_OPTIONS
          value: -javaagent:/opt/aiagent/applicationinsights-agent-3.4.10.jar
        image: cloudfyy/application-insights-java-agent:1.0.19
        imagePullPolicy: IfNotPresent
        name: copy-application-insights-agent-and-config-file
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config/
          name: appinsights-config
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: appinsights-config
status:
  fullyLabeledReplicas: 1
  observedGeneration: 1
  replicas: 1
